development:
  adapter: mysql2
  database: manage_my_keys_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: manage_my_keys_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: manage_my_keys
  pool: 5
  timeout: 5000
